name: addrs
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.11.4
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - cudatoolkit=11.8 # Adjust based on your CUDA version
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - pandas>=1.3.0
  - tqdm>=4.64.0
  - pillow>=9.0.0
  - pyyaml>=6.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - pytest>=6.0.0
  - psutil>=5.8.0
  - pip

  - pip:
      - timm==0.6.7
      - plotly>=5.0.0
      - ipywidgets>=7.6.0
      - black>=22.0.0
      - flake8>=4.0.0
